-- RESPONSABILIDADE: Evoluir o schema, adicionando as tabelas para o Módulo de Vendas.

CREATE TABLE sales (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       sale_date TIMESTAMP WITH TIME ZONE NOT NULL,
                       canal_venda_id BIGINT NOT NULL,
                       total_amount NUMERIC(19, 2) NOT NULL,
                       CONSTRAINT fk_sale_canal_venda FOREIGN KEY (canal_venda_id) REFERENCES canais_venda(id)
);

CREATE TABLE sale_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            sale_id BIGINT NOT NULL,
                            produto_id BIGINT NOT NULL,
                            quantity INT NOT NULL,
                            unit_price NUMERIC(19, 2) NOT NULL,
                            total_price NUMERIC(19, 2) NOT NULL,
                            CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
                            CONSTRAINT fk_sale_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);