-- RESPONSABILIDADE: Refatorar a base de dados para o modelo de "Produção Híbrida".

-- ETAPA 1: REMOVER A ANTIGA ESTRUTURA DE "RECEITA"
-- A tabela composicao_produto torna-se redundante, pois a "receita"
-- passará a viver dentro da própria tabela de produtos.
DROP TABLE IF EXISTS composicao_produto;

-- ETAPA 2: APRIMORAR A TABELA DE PRODUTOS PARA SER O "MOLDE"
ALTER TABLE produtos
    ADD COLUMN tipo_materia_prima_id BIGINT,
    ADD COLUMN largura_cm_unitaria NUMERIC(10, 2),
    ADD COLUMN comprimento_cm_unitario NUMERIC(10, 2);

-- Adiciona a chave estrangeira para ligar o produto ao seu material principal.
ALTER TABLE produtos
    ADD CONSTRAINT fk_produto_tipo_materia_prima
        FOREIGN KEY (tipo_materia_prima_id) REFERENCES tipos_materia_prima(id);

-- ETAPA 3: CRIAR A NOVA TABELA PARA O "PROCESSO DE FABRICO"
-- Esta tabela irá guardar o histórico de cada ordem de produção.
CREATE TABLE ordens_de_corte (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 produto_id BIGINT NOT NULL,
                                 lote_principal_id BIGINT NOT NULL,
                                 quantidade_produzida INT NOT NULL,
                                 modo_calculo VARCHAR(50) NOT NULL,
    -- Dimensões Finais (seja calculado ou manual)
                                 largura_final_cm DOUBLE PRECISION NOT NULL,
                                 comprimento_final_cm DOUBLE PRECISION NOT NULL,
    -- Campos de auditoria
                                 data_criacao TIMESTAMP WITH TIME ZONE NOT NULL,
                                 motivo VARCHAR(255),

                                 CONSTRAINT fk_ordem_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
                                 CONSTRAINT fk_ordem_lote FOREIGN KEY (lote_principal_id) REFERENCES lotes_materia_prima(id)
);
