-- RESPONSABILIDADE: Criar tabela "ordem_de_corte" para registrar histórico de ordens de corte.
-- Esta tabela será usada pelo serviço de produção híbrida para registrar entradas, saídas e sobras.

-- ETAPA 1: CRIAR A TABELA "ordem_de_corte"
CREATE TABLE ordem_de_corte (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                produto_id BIGINT NOT NULL,
                                quantidade INT NOT NULL,
                                data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                motivo VARCHAR(255),

                                CONSTRAINT fk_ordem_de_corte_produto FOREIGN KEY (produto_id)
                                    REFERENCES produtos(id)
                                    ON DELETE RESTRICT
                                    ON UPDATE CASCADE
);
